[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.20"
solc-version = "0.8.20"
via_ir = true
optimizer-runs = 20_000

ffi = true
fs_permissions = [{ access = "read", path = "./test"}, { access = "read", path = "./node_modules"}]

[profile.default.fuzz]
runs = 1_024
